use super::*;

/// Represents cached page metadata returned by the `load_cached_resource` Tauri command.
///
/// Field reads on the rust side go through the `get_*` accessors generated
/// by the `Data` derive (e.g. `get_from_cache()`, `get_cache_path()`) rather
/// than direct field access, matching the house style used by the `euv`
/// crate. `New` derives the `new(...)` constructor for test/builder use;
/// the production call site still uses a struct literal because the
/// field order is more readable inline than the positional `new` args.
#[derive(Data, New, Serialize)]
pub(crate) struct CachedPage {
    /// Whether the page was served from the local cache.
    #[get(pub(crate))]
    pub(crate) from_cache: bool,
    /// The remote URL of the cached page.
    #[get(pub(crate))]
    pub(crate) remote_url: String,
    /// The cache source status (`"active"` or `"none"`).
    #[get(pub(crate))]
    pub(crate) source: String,
    /// The local filesystem path to the active cache directory.
    #[get(pub(crate))]
    pub(crate) cache_path: String,
}

/// Represents the structured result returned by the `update_cache` Tauri command.
///
/// Carries the outcome enum plus a data payload (new snapshot name on
/// success) and a human-readable message (description on success, error
/// detail on failure) so the webview can both drive its retry decision
/// and surface the native-side context to its own logs / UI.
///
/// Like `CachedPage`, rust-side field reads must go through the `get_*`
/// accessors generated by `Data`; `New` provides the `new(...)` constructor.
#[derive(Data, New, Serialize)]
pub(crate) struct CacheUpdateResult {
    /// The outcome of the cache update operation.
    ///
    /// `Success` when a new version snapshot was fetched, written, and staged
    /// to take effect on next launch. `Failed` when the operation did not
    /// produce a usable snapshot (fetch error, write error, oversized payload,
    /// etc.). The webview should treat this as the authoritative status —
    /// `Err(...)` results are reserved for Tauri-side panics / programmer
    /// errors, not normal fetch failures.
    #[get(pub(crate))]
    pub(crate) result: CacheUpdateStatus,
    /// The newly generated version name (`v_<timestamp_millis>`) on success,
    /// or an empty string on failure.
    ///
    /// Same identifier returned by `new_version_name()` — preserved verbatim
    /// so the frontend can correlate with logs / cache directory listings.
    #[get(pub(crate))]
    pub(crate) data: String,
    /// Human-readable detail about the outcome.
    ///
    /// On success this carries the snapshot descriptor; on failure it carries
    /// the underlying error message from the cache layer.
    #[get(pub(crate))]
    pub(crate) message: String,
}
